import { Rotation } from "@/app/types";

export const DEFAULT_ROTATIONS: Rotation[] = [
  {
    id: "wiahcsqysyn",
    name: "Nameless Sword DPS Rotation",
    martialArtId: "bellstrike_splendor",
    skills: [
      {
        entryId: "aks60wyr7x4",
        id: "nameless_homeless_charge_2",
        order: 0,
        count: 1,
      },
      {
        entryId: "45gjibjy1nx",
        id: "nameless_homeless_charge_2",
        order: 1,
        count: 1,
      },
      {
        entryId: "yz67407vsh8",
        id: "nameless_qiankuns_lock",
        order: 2,
        count: 1,
      },
      {
        entryId: "aku8q6u7x3",
        id: "nameless_homeless_charge_2",
        order: 3,
        count: 1,
      },
      {
        entryId: "5suaqxvhztl",
        id: "nameless_homeless_charge_2",
        order: 4,
        count: 1,
      },
      {
        entryId: "gcedvgguf28",
        id: "nameless_homeless_charge_2",
        order: 5,
        count: 1,
      },
      {
        entryId: "sbjdqw18as",
        id: "mystic_soaring_spin",
        order: 6,
        count: 1,
      },
      {
        entryId: "ishl4vod4fn",
        id: "nameless_homeless_charge_2",
        order: 7,
        count: 1,
      },
      {
        entryId: "qhlhsp1rlzl",
        id: "nameless_qiankuns_lock",
        order: 8,
        count: 1,
      },
      {
        entryId: "bj9cxodijr9",
        id: "nameless_homeless_charge_2",
        order: 9,
        count: 1,
      },
      {
        entryId: "owh4nq825dq",
        id: "nameless_homeless_charge_2",
        order: 10,
        count: 1,
      },
      {
        entryId: "6p6407bvm25",
        id: "mystic_soaring_spin",
        order: 11,
        count: 1,
      },
      {
        entryId: "x3tlppn1qka",
        id: "nameless_homeless_charge_2",
        order: 12,
        count: 1,
      },
      {
        entryId: "ctrcbwjzdu",
        id: "nameless_qiankuns_lock",
        order: 13,
        count: 1,
      },
      {
        entryId: "lm6n8om6rdc",
        id: "nameless_homeless_charge_2",
        order: 14,
        count: 1,
      },
      {
        entryId: "i8f5alepx2",
        id: "nameless_homeless_charge_2",
        order: 15,
        count: 1,
      },
      {
        entryId: "tag8ve3sqpg",
        id: "mystic_soaring_spin",
        order: 16,
        count: 1,
      },
      {
        entryId: "itj2b7hc0zc",
        id: "nameless_homeless_charge_2",
        order: 17,
        count: 1,
      },
      {
        entryId: "pwe5n1ogssl",
        id: "nameless_qiankuns_lock",
        order: 18,
        count: 1,
      },
      {
        entryId: "95kv6f043ak",
        id: "nameless_homeless_charge_2",
        order: 19,
        count: 1,
      },
      {
        entryId: "5jbqa4qtuin",
        id: "nameless_homeless_charge_2",
        order: 20,
        count: 1,
      },
      {
        entryId: "o1otww0fk2o",
        id: "mystic_soaring_spin",
        order: 21,
        count: 1,
      },
      {
        entryId: "arenumzfn8",
        id: "nameless_homeless_charge_2",
        order: 22,
        count: 1,
      },
      {
        entryId: "0wyiqsg9dl1",
        id: "nameless_qiankuns_lock",
        order: 23,
        count: 1,
      },
      {
        entryId: "onlpsj3e2jp",
        id: "nameless_homeless_charge_2",
        order: 24,
        count: 1,
      },
      {
        entryId: "asrp6fw87vh",
        id: "nameless_homeless_charge_2",
        order: 25,
        count: 1,
      },
    ],
    activePassiveSkills: [
      "ps_bellstrike_splendor_1",
      "ps_bellstrike_splendor_2",
    ],
    activeInnerWays: [
      "iw_universal_1",
      "iw_universal_2",
      "iw_universal_3",
      "iw_universal_4",
      "iw_universal_5",
      "iw_bellstrike_1",
      "iw_bellstrike_2",
      "iw_silkbind_1",
      "iw_silkbind_2",
      "iw_stonesplit_1",
      "iw_bamboocut_1",
      "iw_bamboocut_2",
    ],
    createdAt: 1767668597551,
    updatedAt: 1767974699259,
  },
];
