import { Skill } from "./types";

export const SKILLS: Skill[] = [
  /* ================= New martial art skills (placeholders) ================= */

  // Heavenquaker Spear — Bellstrike Umbra
  {
    id: "heavenquaker_sweep_all",
    name: "Sweep All",
    martialArtId: "bellstrike_umbra",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "heavenquaker_sober_sorrow",
    name: "Sober Sorrow",
    martialArtId: "bellstrike_umbra",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "heavenquaker_conversion",
    name: "Spear - Conversion",
    martialArtId: "bellstrike_umbra",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "heavenquaker_light",
    name: "Spear - Light Attack",
    martialArtId: "bellstrike_umbra",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "heavenquaker_drifting_thrust",
    name: "Drifting Thrust / Spear - Heavy Attack",
    martialArtId: "bellstrike_umbra",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Infernal Twinblades — Bamboocut Wind
  {
    id: "infernal_calamitys_greed",
    name: "Calamity's Greed",
    martialArtId: "bamboocut_wind",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "infernal_addled_mind",
    name: "Addled Mind",
    martialArtId: "bamboocut_wind",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "infernal_dual_weapon_skill",
    name: "Dual Blades - Dual-Weapon Skill",
    martialArtId: "bamboocut_wind",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "infernal_light_attack",
    name: "Dual Blades - Light Attack / Heaven's Wrath",
    martialArtId: "bamboocut_wind",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "infernal_flamelash",
    name: "Flamelash",
    martialArtId: "bamboocut_wind",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Inkwell Fan — Silkbind Jade
  {
    id: "inkwell_mountain_sky",
    name: "Mountain Sky",
    martialArtId: "silkbind_jade",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "inkwell_jadewind_shield",
    name: "Jadewind Shield",
    martialArtId: "silkbind_jade",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "inkwell_fan_conversion",
    name: "Fan - Conversion",
    martialArtId: "silkbind_jade",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "inkwell_light_attack",
    name: "Fan - Light Attack / Forsaken Fame",
    martialArtId: "silkbind_jade",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "inkwell_heavy_attack",
    name: "Fan - Heavy Attack / Moonlit Spring",
    martialArtId: "silkbind_jade",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Mortal Rope Dart — Bamboocut Wind
  {
    id: "mortal_rodent_rampage",
    name: "Rodent Rampage",
    martialArtId: "bamboocut_wind",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "mortal_bladebound_thread",
    name: "Bladebound Thread",
    martialArtId: "bamboocut_wind",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "mortal_rope_conversion",
    name: "Rope Dart - Conversion",
    martialArtId: "bamboocut_wind",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "mortal_light_attack",
    name: "Rope Dart - Light Attack / Coiled Loong",
    martialArtId: "bamboocut_wind",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "mortal_rodents_resilience",
    name: "Rodent's Resilience",
    martialArtId: "bamboocut_wind",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Nameless Spear — Bellstrike Splendor
  {
    id: "nameless_legion_breaker",
    name: "Legion Breaker",
    martialArtId: "bellstrike_splendor",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_qiankuns_lock",
    name: "Qiankun's Lock",
    martialArtId: "bellstrike_splendor",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_spear_conversion",
    name: "Spear - Conversion",
    martialArtId: "bellstrike_splendor",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_spear_light",
    name: "Spear - Light Attack",
    martialArtId: "bellstrike_splendor",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_storm_dance",
    name: "Storm Dance / Spear - Heavy Attack",
    martialArtId: "bellstrike_splendor",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Nameless Sword — Bellstrike Splendor
  {
    id: "nameless_shadow_step",
    name: "Shadow Step",
    martialArtId: "bellstrike_splendor",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_fearless_lunge",
    name: "Fearless Lunge",
    martialArtId: "bellstrike_splendor",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_sword_conversion",
    name: "Sword - Conversion",
    martialArtId: "bellstrike_splendor",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_sword_light",
    name: "Sword - Light Attack",
    martialArtId: "bellstrike_splendor",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "nameless_homeless_charge",
    name: "Homeless Charge",
    martialArtId: "bellstrike_splendor",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Vernal Umbrella — Silkbind Jade
  {
    id: "vernal_unfaded_flower",
    name: "Unfaded Flower",
    martialArtId: "silkbind_jade",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "vernal_spring_sorrow",
    name: "Spring Sorrow",
    martialArtId: "silkbind_jade",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "vernal_umbrella_conversion",
    name: "Umbrella - Conversion",
    martialArtId: "silkbind_jade",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "vernal_umbrella_light",
    name: "Umbrella - Light Attack / Spring Away",
    martialArtId: "silkbind_jade",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "vernal_apricot_heaven",
    name: "Apricot Heaven / Colorful Phoenix",
    martialArtId: "silkbind_jade",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Panacea Fan — Silkbind Deluge
  {
    id: "panacea_light_dust",
    name: "Light Dust After Morning Rain / Resurrection",
    martialArtId: "silkbind_deluge",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "panacea_mistbound_aid",
    name: "Mistbound Aid / Endless Cloud",
    martialArtId: "silkbind_deluge",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "panacea_fan_conversion",
    name: "Fan - Conversion",
    martialArtId: "silkbind_deluge",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "panacea_fourfold_inquiry",
    name: "Fourfold Inquiry",
    martialArtId: "silkbind_deluge",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "panacea_emerald_dewtouch",
    name: "Emerald Dewtouch",
    martialArtId: "silkbind_deluge",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Soulshade Umbrella — Silkbind Deluge
  {
    id: "soulshade_echoes",
    name: "Echoes of a Thousand Plants",
    martialArtId: "silkbind_deluge",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "soulshade_floating_grace",
    name: "Floating Grace",
    martialArtId: "silkbind_deluge",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "soulshade_umbrella_conversion",
    name: "Umbrella - Conversion",
    martialArtId: "silkbind_deluge",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "soulshade_light_attack",
    name: "Umbrella - Light Attack",
    martialArtId: "silkbind_deluge",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "soulshade_pale_petal",
    name: "Pale Petal / Umbrella Heavy Attack",
    martialArtId: "silkbind_deluge",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Stormbreaker Spear — Stonesplit Might
  {
    id: "stormbreaker_thunder_shock",
    name: "Thunder Shock",
    martialArtId: "stonesplit_might",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "stormbreaker_storm_roar",
    name: "Storm Roar",
    martialArtId: "stonesplit_might",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "stormbreaker_spear_conversion",
    name: "Spear - Conversion",
    martialArtId: "stonesplit_might",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "stormbreaker_spear_light",
    name: "Spear - Light Attack",
    martialArtId: "stonesplit_might",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "stormbreaker_fury_spear",
    name: "Fury Spear / Spear - Heavy Attack",
    martialArtId: "stonesplit_might",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Strategic Sword — Bellstrike Umbra
  {
    id: "strategic_third_track_recoil",
    name: "Third Track Recoil",
    martialArtId: "bellstrike_umbra",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "strategic_inner_track_slash",
    name: "Inner Track Slash",
    martialArtId: "bellstrike_umbra",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "strategic_sword_conversion",
    name: "Sword - Conversion",
    martialArtId: "bellstrike_umbra",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "strategic_sword_light",
    name: "Sword - Light Attack",
    martialArtId: "bellstrike_umbra",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "strategic_second_track_slash",
    name: "Second Track Slash / Sword - Heavy Attack",
    martialArtId: "bellstrike_umbra",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },

  // Thundercry Blade — Stonesplit Might
  {
    id: "thundercry_sunrush_gale",
    name: "Sunrush Gale",
    martialArtId: "stonesplit_might",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "thundercry_predators_shield",
    name: "Predator's Shield / Shifting Heaven",
    martialArtId: "stonesplit_might",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "thundercry_mo_blade_conversion",
    name: "Mo Blade - Conversion",
    martialArtId: "stonesplit_might",
    category: "skill",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "thundercry_light_attack",
    name: "Mo Blade - Light Attack / Galecloud Cleave",
    martialArtId: "stonesplit_might",
    category: "basic",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
  {
    id: "thundercry_avalanche",
    name: "Avalanche",
    martialArtId: "stonesplit_might",
    category: "ultimate",
    hits: [{ physicalMultiplier: 1, elementMultiplier: 1, hits: 1 }],
    notes: "Placeholder multipliers",
  },
];
